services:
  api:
    container_name: redcarpet_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    volumes:
      - ./src:/app/src
    restart: unless-stopped

  prisma-studio:
    container_name: redcarpet_prismastudio
    build:
      context: .
      dockerfile: Dockerfile.prisma-studio
    ports:
      - '5555:5555'
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped

  postgres:
    container_name: redcarpet_postgres
    image: postgres:16-alpine
    ports:
      - '7777:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
